### ISSUE TITLE
Difference from usual GCD calls?

### ISSUE THREAD

**Issue by gerchicov-bp** [JARMourato/Dispatch#11]
according to this article:
https://thatthinginswift.com/background-threads/

the GCD syntax in swift is almost the same as in Objective-C. So could you explain what is the difference in your library?

And I think this info should be added into readme file

**Comment by gabrielPeart** [comment]
@gerchicov-bp 
Our library is a wrapper of `dispatch_async` with a nicer and user friendly API. A main benefit of using our library is that it is an adapter of the built-in API, in Swift 3, Apple is going to change their API and we will cover it in our library, so if you consume our API instead, you won't need to refactor your code.

We will add this info and improve our readme file. Thank you!

**Comment by gerchicov-bp** [comment]
Ok, thanks, this info is enough for me

**Comment by gabrielPeart** [comment]
You are welcome! Hope you will enjoy using Dispatch :)
