### ISSUE TITLE
`after` is not publicly exposed.

### ISSUE THREAD

**Issue by gapl** [JARMourato/Dispatch#14]
Basically what it says in the title. `after` can not be used as it is not exposed, even though it's shown in the README.md example.

**Comment by JARMourato** [comment]
Hi @gapl, which version are you using ? I've just tested the lastest version (0.9.8) and i was able to access _Dispatch.after_  just like in the README.md example

**Comment by gapl** [comment]
Just integrated it today, so latest Podspec version, Dispatch v.0.9.6

**Comment by JARMourato** [comment]
@gapl , your local podspecs may be outdated because the latest version of Dispatch is 0.9.8. To solve your problem please run _pod update_

**Comment by gapl** [comment]
You are 100% correct, all works as it should. Thanks for the fast response :)
