### ISSUE TITLE
Installation options on README

### ISSUE THREAD

**Issue by lfarah** [JARMourato/Dispatch#2]
Hey João, your library is amazing and I can't wait to start using it.

The only minor change I'd do in the `README.md` would be in `Installation`, where I'd also show how to drag and drop the `Dispatch.swift` file.
I created this [iOS Open Source README template](https://github.com/awesome-labs/iOS-readme-template) so you can see how the installation section would look like.

That are your thoughts?

**Comment by JARMourato** [comment]
Thanks for the suggestion @lfarah. 
I've improved `README.md` based on your input.
Nice template btw!

**Comment by lfarah** [comment]
Thanks!
