### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [JARMourato/Dispatch#3]
<img width="350" alt="screen shot 2016-05-24 at 11 40 46 am" src="https://cloud.githubusercontent.com/assets/6511079/15515716/601567ca-21a4-11e6-8fba-c218676a810f.png">
Could be something like:

> Swifty Dispatch Queue Manager :large_orange_diamond:

**Comment by JARMourato** [comment]
Hi @lfarah , thanks for the suggestion. I'll add a description shortly.
